services:
  - type: web
    name: codify-server
    env: node
    buildCommand: |
      apt-get update
      apt-get install -y openjdk-11-jdk
      yarn install
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
